/**
 * server/subagents/protocolResearcher.ts
 *
 * Deep dives on specific DeFi protocols: TVL, audit status, fees, revenue.
 * Uses DefiLlama protocols + fees API (free).
 */

import { runSubAgent, SubAgentRunInput } from '../agent/executor'
import type { LLMTool } from '../llm'

const BASE = 'https://api.llama.fi'

const cache = new Map<string, { value: unknown; expiresAt: number }>()
function cGet<T>(k: string): T | null {
  const e = cache.get(k)
  if (!e || Date.now() > e.expiresAt) { cache.delete(k); return null }
  return e.value as T
}
function cSet(k: string, v: unknown, ttl = 8 * 60_000) { cache.set(k, { value: v, expiresAt: Date.now() + ttl }) }

async function apiFetch<T>(url: string): Promise<T> {
  const cached = cGet<T>(url)
  if (cached) return cached
  const res = await fetch(url, { signal: AbortSignal.timeout(8000) })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const data = await res.json() as T
  cSet(url, data)
  return data
}

const TOOLS: LLMTool[] = [
  {
    name: 'get_protocol_details',
    description: 'Get TVL, category, audits, chains, and 30d TVL change for a DeFi protocol',
    parameters: {
      type: 'object',
      properties: {
        protocol: { type: 'string', description: 'Protocol slug e.g. aave, uniswap, compound, curve, lido' },
      },
      required: ['protocol'],
    },
  },
  {
    name: 'get_protocol_fees',
    description: 'Get daily/weekly fees and revenue generated by a protocol',
    parameters: {
      type: 'object',
      properties: {
        protocol: { type: 'string', description: 'Protocol slug' },
      },
      required: ['protocol'],
    },
  },
  {
    name: 'search_protocols',
    description: 'Search for protocols by name or category',
    parameters: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search term or category (e.g. "lending", "dex", "liquid staking")' },
        chain: { type: 'string', description: 'Optional: filter by chain' },
        limit: { type: 'number', description: 'Max results (default 8)' },
      },
      required: ['query'],
    },
  },
  {
    name: 'compare_protocols',
    description: 'Compare multiple protocols side by side by TVL, fees, and category',
    parameters: {
      type: 'object',
      properties: {
        protocols: { type: 'string', description: 'Comma-separated protocol slugs e.g. "aave,compound,morpho"' },
      },
      required: ['protocols'],
    },
  },
]

export async function runProtocolResearcher(input: Omit<SubAgentRunInput, 'tools' | 'toolHandlers'>) {
  return runSubAgent({
    ...input,
    tools: TOOLS,
    toolHandlers: {
      get_protocol_details: async ({ protocol }) => {
        const slug = String(protocol).toLowerCase()
        const data = await apiFetch<{
          name: string; tvl: number; category: string; audits: number
          change_7d: number; change_1m: number; chains: string[]
          description: string; url: string
        }>(`${BASE}/protocol/${slug}`)
        return {
          name: data.name, category: data.category,
          tvl: `$${(data.tvl / 1e6).toFixed(0)}M`,
          tvlChange7d: `${data.change_7d?.toFixed(1)}%`,
          tvlChange30d: `${data.change_1m?.toFixed(1)}%`,
          audits: data.audits ?? 0,
          chains: data.chains?.slice(0, 6),
          description: data.description?.slice(0, 200),
        }
      },

      get_protocol_fees: async ({ protocol }) => {
        const slug = String(protocol).toLowerCase()
        type FeeData = { total24h: number; total7d: number; total30d: number; revenue24h: number; revenue7d: number }
        const data = await apiFetch<{ protocols: Array<{ name: string; slug: string } & FeeData> }>(`${BASE}/overview/fees`)
        const found = data.protocols?.find(p => p.slug?.toLowerCase() === slug || p.name?.toLowerCase() === slug)
        if (!found) return { error: `No fee data for ${protocol}` }
        return {
          protocol: found.name,
          fees24h: `$${((found.total24h ?? 0) / 1000).toFixed(0)}K`,
          fees7d: `$${((found.total7d ?? 0) / 1000).toFixed(0)}K`,
          fees30d: `$${((found.total30d ?? 0) / 1000).toFixed(0)}K`,
          revenue24h: `$${((found.revenue24h ?? 0) / 1000).toFixed(0)}K`,
          revenue7d: `$${((found.revenue7d ?? 0) / 1000).toFixed(0)}K`,
        }
      },

      search_protocols: async ({ query, chain, limit = 8 }) => {
        const q = String(query).toLowerCase()
        const data = await apiFetch<Array<{ name: string; slug: string; tvl: number; category: string; chains: string[] }>>(`${BASE}/protocols`)
        return data
          .filter(p => {
            const matchesQuery = p.name?.toLowerCase().includes(q) || p.category?.toLowerCase().includes(q)
            const matchesChain = !chain || p.chains?.some((c: string) => c.toLowerCase() === String(chain).toLowerCase())
            return matchesQuery && matchesChain && p.tvl > 0
          })
          .sort((a, b) => b.tvl - a.tvl)
          .slice(0, Number(limit))
          .map(p => ({ name: p.name, slug: p.slug, tvl: `$${(p.tvl / 1e6).toFixed(0)}M`, category: p.category, chains: p.chains?.slice(0, 4) }))
      },

      compare_protocols: async ({ protocols }) => {
        const slugs = String(protocols).split(',').map(s => s.trim().toLowerCase())
        const data = await apiFetch<Array<{ name: string; slug: string; tvl: number; category: string; change_7d: number; audits: number; chains: string[] }>>(`${BASE}/protocols`)
        return slugs.map(slug => {
          const p = data.find(x => x.slug?.toLowerCase() === slug || x.name?.toLowerCase() === slug)
          if (!p) return { slug, error: 'not found' }
          return { name: p.name, tvl: `$${(p.tvl / 1e6).toFixed(0)}M`, category: p.category, change7d: `${p.change_7d?.toFixed(1)}%`, audits: p.audits, chains: p.chains?.slice(0, 3) }
        })
      },
    },
  })
}
